spring:
#  config:
#    activate:
#      on-profile: local
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
#    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
